### ISSUE TITLE
Tracker - Replace encryption/decryption/key generation logic with at_chops

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#1147]
### Describe the bug

Tracker for replacing all encryption/decryption/key generation logic with at_chops impl

### Steps to reproduce

n/a

### Expected behavior

* no references to EncryptionUtil, EncryptionService in SDK/libraries

**Comment by murali-shris** [comment]
- [x] https://github.com/atsign-foundation/at_client_sdk/issues/1141
- [ ] https://github.com/atsign-foundation/at_client_sdk/issues/1145
- [ ] https://github.com/atsign-foundation/at_client_sdk/issues/1146
- [ ] https://github.com/atsign-foundation/at_libraries/issues/429
- [ ] https://github.com/atsign-foundation/at_client_sdk/issues/1566
- [ ] https://github.com/atsign-foundation/at_client_sdk/issues/1565

**Comment by murali-shris** [comment]
Below issue has to be part of major version release in at_lookup
- [ ] https://github.com/atsign-foundation/at_client_sdk/issues/1567

**Comment by gkc** [comment]
Complete
