### ISSUE TITLE
Atkey validation & parsing

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_client_sdk#373]
Lead: @VJag (please update if labeled incorrectly)

**Is your feature request related to a problem? Please describe.**
Right now what makes a key valid is not clearly defined. Idea is to come up with the definition and then implement it in the code.

**Describe the solution you'd like**
The below document captures the thoughts:
https://docs.google.com/document/d/16wQTDo2Lb9G9Pti_LnTc726FlUKO_aMcuIAnkT7iqew/edit?usp=sharing

** Subtasks

 - [x] Define a "Valid Key"
 - [x] Implement the validation of the AtKey
 - [x] Scan every single key in all secondaries to find the complete set of characters currently used, identify all characters which aren't in our allow list and their frequency of use, and then decide for each of those characters whether we want to add to the allow list or not.

**Comment by VJag** [comment]
** Sub tasks

 - [ ] Define a "Valid Key"
 - [ ] Implement the validation of the AtKey
 - [ ] Plug the validation into SDK and the server

**Comment by gkc** [comment]
I added some subtasks to the main issue description following team discussion today

**Comment by VJag** [comment]
Definition of a valid @key is defined here:
https://docs.google.com/document/d/16wQTDo2Lb9G9Pti_LnTc726FlUKO_aMcuIAnkT7iqew/edit?usp=sharing

**Comment by VJag** [comment]
<img width="1336" alt="Screenshot 2022-01-19 at 8 23 50 PM" src="https://user-images.githubusercontent.com/20091120/150155457-943b2672-28ec-4ed2-966a-74853dbee5be.png">

**Comment by VJag** [comment]
Above diagram should give us an idea into where to plug-in the key validations

**Comment by VJag** [comment]
@gkc IMO action plan for the implementation.

1. Implement toString on AtKey and its subclasses to get on the wire representation
2. Implement validators for various key types. This should be in at_commons.
3. AtKey should be validated before and after creation
      3.1. New builders of AtKey should validate the AtKey before the creation
      3.2 Introduce validate() on AtKey to validate after creation
4. Based on the state diagram plug in the key validations on SDK first then on the server

**Comment by gkc** [comment]
Agreed

**Comment by VJag** [comment]
Analysis of the key types and their behaviour:
https://docs.google.com/spreadsheets/d/1EOcF_vznBoKWXxRT8dbeG47RP7wnF30ubwXghganTlk/edit?usp=sharing

**Comment by VJag** [comment]
Burned down an 8 still a 5 to 8 is remaining. Will carry over to this sprint too.

**Comment by sitaram-kalluri** [comment]
The AtKey validation implementation is tracked in [#394](https://github.com/atsign-foundation/at_client_sdk/issues/394). Closing this issue.
