### ISSUE TITLE
(Tracker) GCP/Travelers - Atsign on Marketplace

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/at_client_sdk#644]
### **GOAL: To get revenue by end of Oct 2022**
Context: The use case picked for the ‘pilot’ was ‘cryptographic consent’ where the buyer inputs a few data points on a form and there is digital fetch of the DUNS # after validation and the buyer is asked for a ‘consent’ on the DUNS #
Proposed [workflow](https://docs.google.com/presentation/d/1d-VmgV2hkyBzVk_q-O62IUwHDuxJv5zx56rJa5rVY0w/edit#slide=id.g15344df504a_0_33)

- [x] **Deadline 9/13:** All teams are clear on the specifications/requirements for the three tracks and lay the groundwork for execution. _All Qs should be answered this week._

### **Track 1** - Enable [private purchase](https://docs.google.com/presentation/d/1d-VmgV2hkyBzVk_q-O62IUwHDuxJv5zx56rJa5rVY0w/edit#slide=id.g15344df504a_0_23) of atSigns on GCP
- [x] **Deadline 10/7**: Atsign completes publishing _private purchase_ of atSigns on Marketplace 
- [x] **Deadline 10/14**: Travelers team able to _secure atSigns_ via Marketplace 

### **Track 2** - [Procurement of microservers](https://docs.google.com/presentation/d/1d-VmgV2hkyBzVk_q-O62IUwHDuxJv5zx56rJa5rVY0w/edit#slide=id.g15344df504a_0_49) (atSign Infrastructure Clusters)
- [x] **Deadline 10/7**: Atsign completes publishing _microservers_ on Marketplace (@anthonyvprakash I think we need to procure first?) 
- [x] **Deadline 10/14**: Travelers team able to _secure microservers_ via Marketplace

@athandle has created this ticket for part 1 and 2 : [Click here](https://github.com/atsign-company/at_handle_registrar_web/issues/444)

### **Track 3** - [Cryptographic consent](https://docs.google.com/presentation/d/1d-VmgV2hkyBzVk_q-O62IUwHDuxJv5zx56rJa5rVY0w/edit#slide=id.g15344df504a_0_68) app development
- [x] **Deadline 9/23**: UX and backend logic for [cryptographic consent app](https://docs.google.com/presentation/d/1d-VmgV2hkyBzVk_q-O62IUwHDuxJv5zx56rJa5rVY0w/edit#slide=id.g15344df504a_0_55) 
- [x] **Deadline 10/21**: Travelers team able to test cryptographic consent app

-----------
- [ ] Need to ping Christin on the GCP team connect
- [ ] Need GCP credits?
Market Place
- [ ] What do we want to put up there?
- [ ] Who is going to build it?
- [ ] How do we ensure that Henna and Bill are on the same page?
- [ ] Actually getting it up on Marketplace
- [ ] Who is on our team building this?

**Comment by gkc** [comment]
Placeholder. Will be updated as we get more clarity about what we want to do

**Comment by anthonyvprakash** [comment]
- Need to ping Christin on the GCP team connect
- Need GCP credits?
- Market Place
- What do we want to put up there?
- Who is going to build it?
- How do we ensure that Henna and Bill are on the same page?
- Actually getting it up on Marketplace
- Who is on our team building this?
- Anything missing?

**Comment by athandle** [comment]
Did we make any progress on this from GCP people?

**Comment by ksanty** [comment]
App is being developed in the atCompany org - repo https://github.com/atsign-company/google-travelers-workshops

**Comment by ksanty** [comment]
@gkc @cpswan @anthonyvprakash @athandle I am closing this ticket.  If you have any notes or links to other tickets please add for historical if helpful.
