### ISSUE TITLE
(Tracker) Define and implement clear sync contracts

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#793]
### Is your feature request related to a problem? Please describe.

Sync is a core enabler of our goal of making it possible for clients to be functional while offline from the network. It has been implemented and evolved organically based on a high-level intent.

However we are missing a clear definition of the overall contract and the individual contracts in the pipeline from client to server and back. As a result we continue to encounter bugs as we use the platform in new and interesting ways.

### Describe the solution you'd like

Overall contract is "clients and servers commit logs should be the same (in terms of AtKey-to-CommitID map at least) when they are 'in sync' for a given regex"

Clear definition of the 7 technical contracts involved in making sync work
  * (Client) How items are added to the 'uncommitted' queue on the client side (upon data store operations)
  * (Client) How the client processes that uncommitted queue (while sending updates to server) - e.g. how is the queue ordered, how is it de-duped, etc
  * (Server) How the server processes updates from the client (including the responses it generates) and what the expectations are - i.e. can we reject? what happens when we reject? and more
  * (Server) How items are added to the commit log on the server such that they are available for sync to the clients
  * (Server) How the server processes that log (when sending updates to client) - e.g. again ordering, de-duping, etc
  * (Client) How the client processes updates from the server - can the client reject? under what conditions? what happens upon a rejection?
  * The 7th contract is the contract for precisely how the client and server exchange information. Currently this is implemented using the batch verb and has state like 'syncInProgress' and 'isInSync'. (Aside: Fsync will implement this contract in a streaming fashion bidirectionally.)

### High-level tasks (please add additional tasks here!)
- [x] [Analyze the current sync unit tests and review the sync contract](https://github.com/atsign-foundation/at_client_sdk/issues/798)
- [x] [Define each of the 7 contracts by defining assertions in test cases for each one.](https://github.com/atsign-foundation/at_client_sdk/issues/794)
  * Specifically these can largely be unit tests which are testing code contracts
- [x] [Verify the contracts by implementing all of the test cases](https://github.com/atsign-foundation/at_client_sdk/issues/795). (Will require substantial amount of work to make things testable by being able to separate key responsibilities in line with the sync contracts)
- [ ] (Re-)define a small number of functional tests which prove integrity of the 7 contracts for a single atSign with two clients
- [ ] (Re-)define a small number of end-to-end tests which have two atSigns, each with (at least) two clients, where we throw the kitchen sink at the tests in terms of operations and their sequence, preferably in a semi-random way, and at the end wait for syncing to complete and then assert the overall contract is being adhered to - i.e. all clients and servers are in sync for a given regex.
- [ ] High-level marketing / outbound comms plan (how do we talk about this, why it's important, why it's cool, how to use it, etc)
- [ ] Clear explanation of the sync subsystem on docs.atsign.com
- [ ] Text or video (or both) content for posting on social or our website
