### ISSUE TITLE
(Tracker) Uplift to docs.atsign.com

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#799]
### Is your feature request related to a problem? Please describe.

Our docs on docs.atsign.com are not sufficient right now. For example we need more explanation about what is going on under the hood so that developers can more easily grasp the programming model and the resulting keystore operations and data flows within clients, between clients and cloud servers, and between cloud servers

### Describe the solution you'd like

More and better docs - explanation, example and guide docs - at docs.atsign.com

### High-level tasks (please add additional tasks here!)
- [ ] In pairs or trios, [review the content](https://github.com/atsign-foundation/at_client_sdk/issues/800) at docs.atsign.com section by section, creating tickets as required for corrections, clarifications or missing content
- [ ] Tickets
  - [ ] [Gary] Create a quickly digestible explanation of how things work from a developer's perspective
- [ ] Plan for whether and how we need to talk about this externally when it's done
- [ ] Work through the tickets
- [ ] Outbound comms (socials, blog posts, etc)

Superceded by [docs#1](https://github.com/atsign-foundation/docs/issues/1)

**Comment by gkc** [comment]
Marking as High priority following conversation with @XavierChanth last week

**Comment by xavierchanth** [comment]
https://docs.google.com/document/d/1SAxsT6WgXFh_uyYtWKWKUyZsVCAk3xaxfmKyObvO41I/edit
