### ISSUE TITLE
[Tracker] ToDo's in the at_client sync unit tests

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_client_sdk#860]
This is a base git issue to list out all the refactoring/enhancements that are identified during the analysis in the sync unit tests in the at_client.

```[tasklist]
### Things to refactor/enhancements
- [x] ~~Add a new method to verify if the client and server are in sync which returns an enum - https://github.com/atsign-foundation/at_client_sdk/issues/832~~
- [x] Add `description` to the KeyInfo to add additional notes about the key - https://github.com/atsign-foundation/at_client_sdk/issues/833
- [ ] Optimized sync process by skipping keys which have commitOp.Update and Commit.Delete and the keys are not synced to the server earlier (Enhancement Request).
- [x] Add validation to check if the key is an Invalid key before adding a key to the sync batch request.
- [ ] Refactor the sync_service code to test the following scenarios: [See list below]
- [x] Update all the available metadata fields and assert - At the moment, there is a known issue where version and createdAt, createdBy and updatedBy fields do not show correct info. https://github.com/atsign-foundation/at_server/issues/1126
```

```[tasklist]
### Refactor SyncService: Skip the sync process when any of the following conditions are met: 
- [ ] When the sync is already running
- [ ] When there is no network
- [ ] Server and Client are InSync
- [ ] Sync request threshold is not met
```

```[tasklist]
### Things to discuss
- [x] At the moment, deleting a non-existent would add an entry to the commit log. Should we throw an exception and not add an entry to the commit-log?
- [ ] Should we have a scenario on deletion and re-creation on the `encryptionPrivateKey` and `PKAMPrivateKey`
- [ ] Need to figure out a way to pause sync to perform assertions (if that is even possible)
- [ ] With TBB set to a key, when sync triggers and TTB of the key is not met, we still fetch the actual value from the keystore for the sync process (we do not return data: null to sync because that would cause the key with null value getting created in the cloud secondary). Is this fine?
```

**Comment by sitaram-kalluri** [comment]
The following issue, https://github.com/atsign-foundation/at_client_sdk/issues/832 is not a priority. Hence moved to backlog. Striking from the above template - "Things to refactor/enhancement"

**Comment by sitaram-kalluri** [comment]
We have sync unit tests in place. Closing this issue here.
